## Домашняя работа №2

## Матрицы и матричные операции.

#### ЧАСТЬ 1

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.  

In [1]:
import numpy as np

а) произведение матриц не определено, т.к. в обоих случаях количество столбцов одной матрицы не равно количеству строк другой матрицы

In [2]:
# b) произведение ВA не определено
# АB =>
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
b = np.array([[9, 10, 19], [11, 12, 20], [13, 14, 21], [15, 16, 22], [17, 18, 23]])
print(f'Матрица A:\n{a}')
print(f'Матрица B:\n{b}')
print(f'Матрица AВ\n{np.dot(a,b)}')

Матрица A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Матрица B:
[[ 9 10 19]
 [11 12 20]
 [13 14 21]
 [15 16 22]
 [17 18 23]]
Матрица AВ
[[215 230 325]
 [540 580 850]]


In [3]:
# проверка расчета вручную
c1=[]
c2=[]
c=[]
c1.append(9*1 + 11*2 + 13*3 + 15*4 + 17*5)
c1.append(10*1 + 12*2 + 14*3 + 16*4 + 18*5)
c1.append(19*1 + 20*2 + 21*3 + 22*4 + 23*5)
c2.append(9*6 + 11*7 + 13*8 + 15*9 + 17*10)
c2.append(10*6 + 12*7 + 14*8 + 16*9 + 18*10)
c2.append(19*6 + 20*7 + 21*8 + 22*9 + 23*10)
c.append(c1)
c.append(c2)
ab = np.array(c)
print(f'Матрица AB:\n{ab}')

Матрица AB:
[[215 230 325]
 [540 580 850]]


In [4]:
def new_matrix(m1,m2):
    a=m2
    b=m1
    
    print(f'Матрица A:\n{a}')
    print(f'Матрица B:\n{b}')
    iter_row = int(a.shape[0])
    iter_col = int(a.shape[1])
    ab=[]
    for i in range(iter_col):
        el=[]
        for k in range(iter_col):
            ss=0
            for j in range(iter_row):            
                    ss+=(a[j,k] * b[i,j])
                    #print(j,i,a[j,k],i,j,b[i,j],a[j,k]*b[i,j])
            el.append(ss)
            #print(ss)
        ab.append(el)
    ab=np.array(ab)
    return ab



In [5]:
# в) оба произведения определены
# BA =>
a = np.array([[9, 10, 19], [11, 12, 20], [13, 14, 21], [15, 16, 22], [17, 18, 23], [2,45,2], [3,7,1], [11,21,41]])
b = np.array([[1, 2, 3, 4, 5, 6, 7, 8], [9, 10, 11, 12, 13, 14, 15, 16], [17, 18, 19, 20, 21, 22, 23, 24]])
   
new_matrix(b,a) 

Матрица A:
[[ 9 10 19]
 [11 12 20]
 [13 14 21]
 [15 16 22]
 [17 18 23]
 [ 2 45  2]
 [ 3  7  1]
 [11 21 41]]
Матрица B:
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]


array([[ 336,  717,  672],
       [ 984, 1861, 1864],
       [1632, 3005, 3056]])

In [6]:
print(f'Матрица ВA:\n{np.dot(b,a)}')

Матрица ВA:
[[ 336  717  672]
 [ 984 1861 1864]
 [1632 3005 3056]]


In [7]:
# AB =>
new_matrix(a,b) 

Матрица A:
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Матрица B:
[[ 9 10 19]
 [11 12 20]
 [13 14 21]
 [15 16 22]
 [17 18 23]
 [ 2 45  2]
 [ 3  7  1]
 [11 21 41]]


array([[ 422,  460,  498,  536,  574,  612,  650,  688],
       [ 459,  502,  545,  588,  631,  674,  717,  760],
       [ 496,  544,  592,  640,  688,  736,  784,  832],
       [ 533,  586,  639,  692,  745,  798,  851,  904],
       [ 570,  628,  686,  744,  802,  860,  918,  976],
       [ 441,  490,  539,  588,  637,  686,  735,  784],
       [  83,   94,  105,  116,  127,  138,  149,  160],
       [ 897,  970, 1043, 1116, 1189, 1262, 1335, 1408]])

In [8]:
print(f'Матрица AB:\n{np.dot(a,b)}')

Матрица AB:
[[ 422  460  498  536  574  612  650  688]
 [ 459  502  545  588  631  674  717  760]
 [ 496  544  592  640  688  736  784  832]
 [ 533  586  639  692  745  798  851  904]
 [ 570  628  686  744  802  860  918  976]
 [ 441  490  539  588  637  686  735  784]
 [  83   94  105  116  127  138  149  160]
 [ 897  970 1043 1116 1189 1262 1335 1408]]


In [9]:
# г)АВ=>
a = np.array([[9, 10, 19, 16], [11, 12, 20, 19], [13, 14, 21, 24], [15, 16, 22, 7]])
b = np.array([[1, 2, 3, 4], [9, 10, 11, 12], [21, 22, 23, 24], [29, 30, 31, 32]])
   
new_matrix(a,b) 

Матрица A:
[[ 1  2  3  4]
 [ 9 10 11 12]
 [21 22 23 24]
 [29 30 31 32]]
Матрица B:
[[ 9 10 19 16]
 [11 12 20 19]
 [13 14 21 24]
 [15 16 22  7]]


array([[ 962, 1016, 1070, 1124],
       [1090, 1152, 1214, 1276],
       [1276, 1348, 1420, 1492],
       [ 824,  884,  944, 1004]])

In [10]:
print(f'Матрица AB:\n{np.dot(a,b)}')

Матрица AB:
[[ 962 1016 1070 1124]
 [1090 1152 1214 1276]
 [1276 1348 1420 1492]
 [ 824  884  944 1004]]


In [11]:
# BA=>   
new_matrix(b,a) 

Матрица A:
[[ 9 10 19 16]
 [11 12 20 19]
 [13 14 21 24]
 [15 16 22  7]]
Матрица B:
[[ 1  2  3  4]
 [ 9 10 11 12]
 [21 22 23 24]
 [29 30 31 32]]


array([[ 130,  140,  210,  154],
       [ 514,  556,  866,  682],
       [1090, 1180, 1850, 1474],
       [1474, 1596, 2506, 2002]])

In [12]:
print(f'Матрица AB:\n{np.dot(b,a)}')

Матрица AB:
[[ 130  140  210  154]
 [ 514  556  866  682]
 [1090 1180 1850 1474]
 [1474 1596 2506 2002]]


__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [13]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

new_matrix(a,b) 

Матрица A:
[[ 4 -1]
 [ 0  5]]
Матрица B:
[[ 1 -2]
 [ 3  0]]


array([[  4, -11],
       [ 12,  -3]])

In [14]:
print(f'Матрица по numpy AB:\n{np.dot(a,b)}')

Матрица по numpy AB:
[[  4 -11]
 [ 12  -3]]


In [15]:
# сумма матриц
# c11 = a11+b11 = 4+1=5
# c12 = a12+b12 = -1 + (-2) = -3
# c21 = a21+b21 = 0+3 = 3
# c22 = a22+b22 = 5 - 0 = 5
c = np.array([[5, -3], [3, 5]])
c

array([[ 5, -3],
       [ 3,  5]])

In [16]:
print(f'Матрица С = A + B\n{a + b}')

Матрица С = A + B
[[ 5 -3]
 [ 3  5]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [17]:
a = np.array([[1,7], [3,-6]])
b = np.array([[0,5], [2,-1]])
c = np.array([[2,-4], [1,1]])
a3 = 3*a
print(a3)
b2 = -2*b
print(b2)
c4 = 4*c
print(c4)
print('Линейная комбинация:')
print(a3+b2+c4)

[[  3  21]
 [  9 -18]]
[[  0 -10]
 [ -4   2]]
[[  8 -16]
 [  4   4]]
Линейная комбинация:
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [18]:
a = np.array([[4,1], [5,-2], [2,3]])
a.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [19]:
print(f'Матрица по numpy AT*A:\n{np.dot(a.T,a)}')

Матрица по numpy AT*A:
[[45  0]
 [ 0 14]]


In [20]:
new_matrix(a.T,a) 

Матрица A:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Матрица B:
[[ 4  5  2]
 [ 1 -2  3]]


array([[45,  0],
       [ 0, 14]])

In [21]:
print(f'Матрица по numpy A*AT:\n{np.dot(a, a.T)}')

Матрица по numpy A*AT:
[[17 18 11]
 [18 29  4]
 [11  4 13]]


In [22]:
new_matrix(a,a.T)

Матрица A:
[[ 4  5  2]
 [ 1 -2  3]]
Матрица B:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]


array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

#### ЧАСТЬ 2

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

a)
$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sinx*sinx - (cosx*-cosx)=sin^2x+cos^2x=1;$$

In [23]:
#б)
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Определитель:
180


$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}=
4\cdot\begin{vmatrix}
5 & 1\\ 
0 & 9
\end{vmatrix} - 
2\cdot\begin{vmatrix}
0 & 1\\ 
0 & 9
\end{vmatrix}+
3\cdot\begin{vmatrix}
0 & 5\\ 
0 & 0
\end{vmatrix}=4*(5*9-0*1)-2*(0*9-0*1)+3*(0*0-0*5)=4*45-0+0=180;$$
$$ или = 4*5*9 =180$$

In [24]:
#в)
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Определитель:
-0


$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}=
1\cdot\begin{vmatrix}
5 & 6\\ 
8 & 9
\end{vmatrix} - 
2\cdot\begin{vmatrix}
4 & 6\\ 
7 & 9
\end{vmatrix}+
3\cdot\begin{vmatrix}
4 & 5\\ 
7 & 8
\end{vmatrix}=1*(5*9-8*6)-2*(4*9-7*6)+3*(4*8-7*5)=
1*(45-48)-2*(36-42)+3*(32-35)=-3+12-9=0;$$


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$=> представим $det(A*A) = det(A)*det(A)=4*4=16$;
    
   б) $det(A^{T}) $ => Определитель транспонированной_ матрицы_ равен_ определителю исходной = 4;
    
   в) $det(2A)$=> Если A-матрица n × n, а k-любая константа, то $det(kA)=k^n(det(A))$. Поэтому $det(2A) = 2^3*4 = 24.$
  

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.



In [25]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Определитель:
0


Ответ: матрица вырожденная, т.к. определитель равен 0

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [26]:
x = [1, 2, 3]
y = [1, 1, 1]
z = [2, 3, 4]

a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


In [27]:
x = [0, 0, 2, 1]
y = [0, 0, 2, 2]
z = [0, 0, 4, 3]
x = [2, 3, 5, 6]

a = np.array([x, y, z, x])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
