### Домашнее задание №4

# Системы линейных уравнений

# часть 1

_1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$



Запишем расширенную матрицу системы:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Путем элементарных преобразований постараемся привести матрицу к ступенчатому виду.

Вычтем из второй строки первую, умноженную на 2:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Отнимем от третьей строки первую:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$



Полученная система будет иметь вид

$$\begin{cases}
x_{1}+x_{2}-x_{3}- 2x_{4}=0, \\
~~~~~~~-x_{2}+x_{3}+5x_{4}=-2, \\
~~~~~~~~~~-2x_{3}+3x_{4}=4. \\
\end{cases}$$

Приняв $x_{4}=c$, получим общее решение системы:

$$x_{4}=c$$

$$x_{3} = (4-3c)/-2=-2+3/2c=3/2c-2,$$

$$-x_{2} + 3/2c - 2 + 5c = -2 => x_{2} = 13/2c$$

$$x_{1} + 13/2c - 3/2c + 2 - 2c = 0 =>  x_{1} + 3c + 2 = 0 =>$$
$$x_{1} = -2-3c$$

при $c=0$
$$x_{1}=-2$$
$$x_{2}=0$$
$$x_{3}=-2$$
$$x_{4}=0$$
подставляя в уравнение - получаем частное решение $c(-2,0,-,0)$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$




In [1]:
import numpy as np

In [2]:
def examination(a,b):
    n = a.shape[0]
    print(f'n : {n}')
    ra= np.linalg.matrix_rank(a)
    print(f'Ранг матрицы a: {ra}')
    rb= np.linalg.matrix_rank(b)
    print(f'Ранг матрицы b: {rb}')
    if ra==rb:
        if ra==rb==n:
            print('Совместная определенная система им. ед решение')
        else:
            print('Совместная неопределенная система им. множество решений')
    else:
        print('НЕсовместная система не им. решений')

In [3]:
#a)
a = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
b = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])
examination(a,b)

n : 3
Ранг матрицы a: 3
Ранг матрицы b: 3
Совместная определенная система им. ед решение


In [4]:
#б)
a = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
b = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])
examination(a,b)

n : 3
Ранг матрицы a: 1
Ранг матрицы b: 2
НЕсовместная система не им. решений


In [5]:
#в)
a = np.array([[1, 2, 5], [3, 1, -8]])
a = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])
examination(a,b)

n : 2
Ранг матрицы a: 2
Ранг матрицы b: 2
Совместная определенная система им. ед решение


__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$



In [6]:
a = np.array([[2, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0,0,0,2]])
b = np.array([[2, 3, -2, 4,3], [0, 5, 0, 1,2], [0, 0, 3, 0,4], [0,0,0,2,1]])
examination(a,b)

n : 4
Ранг матрицы a: 4
Ранг матрицы b: 4
Совместная определенная система им. ед решение


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

Сложим 1 и 3 строки:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
8 & 10 & 12
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
a+c
\end{matrix}
\end{pmatrix}.$$

от 3 отнимем 2*2

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
(a+c)-2b
\end{matrix}
\end{pmatrix}.$$

In [7]:
a,b,c = 0,1,0
x = np.array([[1, 2, 3], [4, 5, 6], [0, 0, 0]])
y = np.array([[1, 2, 3, a], [4, 5, 6, b], [0, 0, 0, (a+c)-2*b]])
examination(x,y)

n : 3
Ранг матрицы a: 2
Ранг матрицы b: 3
НЕсовместная система не им. решений


# часть 2

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [8]:
#a)
a = np.array([[1, -2], [3, -4]])
a1 = np.array([[1, -2], [7, -4]])
a2 = np.array([[1, 1], [3, 7]])
print(f'Определитель:{np.linalg.det(a):.0f}')
print(f'Определитель:{np.linalg.det(a1):.0f}')
print(f'Определитель:{np.linalg.det(a2):.0f}')
print(f'x1 = {np.linalg.det(a1)/np.linalg.det(a):.0f}')
print(f'x2 = {np.linalg.det(a2)/np.linalg.det(a):.0f}')

Определитель:2
Определитель:10
Определитель:4
x1 = 5
x2 = 2


In [9]:
#б)
a = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
a1 = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
a2 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
a3 = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])
print(f'Определитель:{np.linalg.det(a):.0f}')
print(f'Определитель:{np.linalg.det(a1):.0f}')
print(f'Определитель:{np.linalg.det(a2):.0f}')
print(f'Определитель:{np.linalg.det(a3):.0f}')
print(f'x1 = {np.linalg.det(a1)/np.linalg.det(a):.0f}')
print(f'x2 = {np.linalg.det(a2)/np.linalg.det(a):.0f}')
print(f'x3 = {np.linalg.det(a3)/np.linalg.det(a):.0f}')

Определитель:43
Определитель:86
Определитель:-43
Определитель:43
x1 = 2
x2 = -1
x3 = 1


__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    


отнимем из 2 строку 1*2:

$$\begin{pmatrix}
1 & 2 & 3\\ 
0 & 5 & 4\\ 
3 & 26 & 30
\end{pmatrix}$$

отнимем из 3 строку 1*3:

$$\begin{pmatrix}
1 & 2 & 3\\ 
0 & 5 & 4\\ 
0 & 20 & 21
\end{pmatrix}$$

отнимем из 3 строку 2*4:

$$\begin{pmatrix}
1 & 2 & 3\\ 
0 & 5 & 4\\ 
0 & 0 & 5
\end{pmatrix}$$

Матрица L:
$$\begin{pmatrix}
1 & 0 & 0\\ 
2 & 1 & 0\\ 
3 & 4 & 1
\end{pmatrix}$$

   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$
    

отнимем из 2 строку 1*2:

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

отнимем из 3 строку 1*3:

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
4 & 22 & 53 & 33
\end{pmatrix}$$

отнимем из 4 строку 1*4:

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}$$

отнимем из 3 строку 2*5:

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 18 & 45 & 17
\end{pmatrix}$$

отнимем из 4 строку 2*6:

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 45 & 47
\end{pmatrix}$$

отнимем из 4 строку 3*15:

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 32
\end{pmatrix}$$

Матрица L:
$$\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 15 & 1
\end{pmatrix}$$

__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$



$$\begin{pmatrix}
2 & 1 & 3\\ 
11 & 7 & 5\\ 
9 & 8 & 4
\end{pmatrix}$$

In [10]:
# расчет ручным способом
a = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
l = np.array([[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
u = np.array([[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]])
y = np.array([[0.],[0.],[0.]])
b = np.array([[1],[-6],[-5]])

a_11 = a[0,0]
a_12 = a[0,1]
a_13 = a[0,2]
a_21 = a[1,0]
a_22 = a[1,1]
a_23 = a[1,2]
a_31 = a[2,0]
a_32 = a[2,1]
a_33 = a[2,2]
l_11 = a_11
l_21 = a_21
l_31 = a_31
u_12 = a_12 / l_11
u_13 = a_13 / l_11
l_22 = a_22 - l_21 * u_12
l_32 = a_32 - l_31 * u_12
u_23 = (a_23 - l_21* u_13)/l_22
l_33 = a_33 -l_31 * u_13 - l_32 * u_23
u_33 = (a_33 - l_31 * u_13 - l_32 * u_23) / l_33
print (f'проверка u_33 = {u_33}')

проверка u_33 = 1.0


In [11]:
l[0,0] = l_11
l[1,0] = l_21
l[1,1] = l_22
l[2,0] = l_31
l[2,1] = l_32
l[2,2] = l_33

In [12]:
u[0,1]  = u_12
u[0,2]  = u_13
u[1,2]  = u_23

In [13]:
print(a)
print(f'L=:\n{l}')
print(f'U=:\n{u}')
print(f'b=:\n{b}')

[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]
L=:
[[ 2.          0.          0.        ]
 [11.          1.5         0.        ]
 [ 9.          3.5        17.33333333]]
U=:
[[ 1.          0.5         1.5       ]
 [ 0.          1.         -7.66666667]
 [ 0.          0.          1.        ]]
b=:
[[ 1]
 [-6]
 [-5]]


In [14]:
y[0] = b[0]/l_11
y[1] = (b[1] - l_21 * y[0]) / l_22
y[2] = (b[2] - l_31 * y[0] - l_32 * y[1])/l_33
print(y)

[[ 0.5       ]
 [-7.66666667]
 [ 1.        ]]


In [15]:
x3 = y[2]
x2 = y[1] - u_23 * x3
print(y[1], u_23, x3)
x1 = y[0] - u_12* x2 - u_13*x3

print(f'x1 = {x1}')
print(f'x2 = {x2}')
print(f'x3 = {x3}')

[-7.66666667] -7.666666666666667 [1.]
x1 = [-1.]
x2 = [0.]
x3 = [1.]


проверка
$$9x_{1}+8x_{2}+4x_{3}=-5$$

In [16]:
# проверка уравнения
9*x1+8*x2+4*x3

array([-5.])

In [17]:
# проверка L*U = A
l.dot(u)

array([[ 2.,  1.,  3.],
       [11.,  7.,  5.],
       [ 9.,  8.,  4.]])

__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$



$$\begin{pmatrix}
81 & -45 & 45 \\ 
-45 & 50 & -15 \\ 
45 & -15 & 38
\end{pmatrix}$$

In [18]:
import math
def matr(a):
    n = a.shape[0]
    u = np.zeros((n,n))
    for i in range(n):        
        if i==0:
            u[i,i] = math.sqrt(a[i,i])
            for j in range(1,n,1):
                u[i,j] = a[i,j] / u[i,i]
        else:
            if i==1:
                u[i,i]=math.sqrt(a[i,i]-u[i-1,i]**2)
                sm = u[i-1,i] * u[i-1,i+1]                
                u[i,i+1]=(a[i,i+1]-sm)/u[i,i]                
            else:
                u[i,i] = math.sqrt(a[i,i] - u[i-2,i]**2 - u[i-1,i]**2)
                        
    return u

In [19]:
a = np.array([[81,-45,45],[-45,50,-15],[45,-15,38]])
#a = np.array([[2,1,4],[1,1,3],[4,3,14]])
#b = np.array([[16],[12],[52]])
b = np.array([[531],[-460],[193]])
print(a)
U = matr(a)
UT = U.T
print(UT)

[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]
[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]]


In [20]:
y1 = b[0]/UT[0,0]
y2 = (b[1] - UT[1,0]*y1)/UT[1,1]
y3 = (b[2] - UT[2,0]*y1 - UT[2,1]*y2)/UT[2,2]
print(y1,y2,y3)

[59.] [-33.] [-12.]


In [21]:
x3 = y3 / U[2,2]
x2 = (y2 - U[1,2]*x3)/U[1,1]
x1 = (y1 - U[0,2]*x3 - U[0,1]*x2)/U[0,0]
print("x1=",x1,"x2=",x2,"x3=",x3)

x1= [6.] x2= [-5.] x3= [-4.]


проверка$$45x_{1}-15x_{2}+38x_{3}=193$$

In [22]:
45*x1-15*x2+38*x3

array([193.])

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.