### Домашнее задание №5

# Сингулярное разложение матриц

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$


In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [2]:
A = np.array([[1,2,0],
              [0,0,5],
              [3,-4,2],
             [1,6,5],
             [0,1,0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [3]:

U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [4]:
print(f'Матрица D:\n{D}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [5]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [6]:
# Убедимся, что она действительно ортогональна
print(np.dot(U.T, U))

[[ 1. -0.  0.  0.  0.]
 [-0.  1. -0. -0. -0.]
 [ 0. -0.  1.  0. -0.]
 [ 0. -0.  0.  1. -0.]
 [ 0. -0. -0. -0.  1.]]


In [7]:
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [8]:
# Убедимся, что она действительно ортогональна
print(np.dot(V.T, V))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# Проведем проверку
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2. -0.]
 [-0.  0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [ 0.  1.  0.]]


2. Для матрицы из предыдущего задания найти:

а) евклидову норму;
    
$$\left \| A \right \|_{E}=\mu_{1}.$$
    

In [10]:
from numpy.linalg import norm
print(f'евклидова норма (встроенная функция) a: {norm(A, ord = 2)}')
print(f'евклидова норма (по формуле) a: {D[0,0]}')

евклидова норма (встроенная функция) a: 8.824868854820442
евклидова норма (по формуле) a: 8.824868854820448


б) норму Фробениуса.
    
$$\left \| A \right \|_{F}=\sqrt{\sum_{k=1}^{r}\mu_{k}^{2}}.$$

In [11]:
import math
sum_mu=0
for i in range(D.shape[1]):    
    sum_mu += D[i,i]**2
norma_f = math.sqrt(sum_mu)
print(f'нормa Фробениуса (встроенная функция)a: {norm(A, ord = "fro")}')
print(f'нормa Фробениуса (по формуле) a: {norma_f}')

нормa Фробениуса (встроенная функция)a: 11.045361017187261
нормa Фробениуса (по формуле) a: 11.045361017187265
